import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
await page.goto('file:///root/site-audit/og-site-v3.html', { waitUntil: 'load' });
await page.waitForTimeout(1500);
await page.evaluate(() => go('investors'));
await page.waitForTimeout(1200);
await page.evaluate(() => document.querySelector('.clip').click());
await page.waitForTimeout(2000);
await page.screenshot({ path: 'lb-calm.png' });
await browser.close();
